AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  flights-app

  SAM Template for flights-app

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Handler: app.lambda_handler

Resources:

  FlightsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flights
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: src_ap
        AttributeType: S
      - AttributeName: plane_iata
        AttributeType: S
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: src_ap-index
        KeySchema:
        - AttributeName: src_ap
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
      - IndexName: plane_iata-index
        KeySchema:
        - AttributeName: plane_iata
          KeyType: HASH
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: DDBTableGroupKey-DataModeling
          Value: DataModeling
  
  AirportByNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: airport_by_name/
      Policies:
      - DynamoDBReadPolicy:
          TableName: flights
      Events:
        AirportByName:
          Type: Api
          Properties:
            Path: /airportByName
            Method: get

  AirportByCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: airport_by_code/
      Policies:
      - DynamoDBReadPolicy:
          TableName: flights
      Events:
        AirportByCode:
          Type: Api
          Properties:
            Path: /airportByCode
            Method: get

  FlightsByCodesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flights_by_codes/
      Policies:
      - DynamoDBReadPolicy:
          TableName: flights
      Events:
        AirportByCode:
          Type: Api
          Properties:
            Path: /flightsByCodes
            Method: get

  FlightsByPlaneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flights_by_plane/
      Policies:
      - DynamoDBReadPolicy:
          TableName: flights
      Events:
        AirportByCode:
          Type: Api
          Properties:
            Path: /flightsByPlane
            Method: get

  OutboundByAirportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: outbound_by_airport/
      Policies:
      - DynamoDBReadPolicy:
          TableName: flights
      Events:
        AirportByCode:
          Type: Api
          Properties:
            Path: /outboundByAirport
            Method: get

Outputs:
  ApiProd:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

